HastaneOtomasyonu/Controllers/loginController.cs
using HastaneOtomasyonu.DataAccessLayer;
using HastaneOtomasyonu.EntityLayer.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace HastaneOtomasyonu.Controllers
{
    public class loginController : Controller
    {
        Context c = new Context();
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Giris g)
        {
            var cc = c.Girises.FirstOrDefault(x=>x.Username == g.Username && x.Password == g.Password);
            if (cc != null)
            {
                HttpContext.Session.SetString("PersonelStatus", cc.Personel.Status.ToString());
                return RedirectToAction("Index","Admin");
            }
            return View();
        }
    }
}

HastaneOtomasyonu/Views/login/Index.cshtml
@model HastaneOtomasyonu.EntityLayer.Models.Entity.Giris
@{
    Layout = null;
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

@using (Html.BeginForm("Index", "login", FormMethod.Post))
{
    <div style="width:30em; height:20em;margin:auto;margin-top:5em">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Username</label>
            <input type="text" name="Username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="Password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Log in</button>
        </div>
    </div>
}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>