HastaneOtomasyonu/Controllers/HastaKayıtController.cs
using HastaneOtomasyonu.BusinessLayer;
using HastaneOtomasyonu.DataAccessLayer;
using HastaneOtomasyonu.EntityLayer.Models.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Cryptography;
using System.Text;

namespace HastaneOtomasyonu.Controllers
{
    public class HastaKayıtController : Controller
    {
        Context c = new Context();
        Encrypte e = new Encrypte();

        [HttpGet]
        public IActionResult Index()
        {
                return View();
        }

        [HttpPost]
        public IActionResult Index(Hasta p)
        {
            string cc = Sorgula(p);
            return RedirectToAction(cc);
        }

        public string Sorgula(Hasta p)
        {
            var EHastaTCNO = Encrypte.Encrypt(p.HastaTCNO);
            var cc = c.Hastas.FirstOrDefault(x => x.HastaTCNO == EHastaTCNO);
            if (cc != null)
            {
                TempData["Hasta"] = cc.HastaID;
                return "PoliklinikSec";
            }
            else
            {
                return "HastaEkle";
            }
        }

        public IActionResult Randevu(int id)
        {
            TempData["pid"] = id;
            var cc = c.Kliniks.Where(x=>x.PoliklinikID == id).ToList();
            return View(cc);
        }

        public IActionResult RandevuAlındı(int id)
        {
            Muayane muayane = new Muayane();
            var hastaId = TempData["Hasta"];
            muayane.MuayaneZamanı = DateTime.Now;
            muayane.HastaID = (int)hastaId;
            muayane.KlinikID = id;
            muayane.PoliklinikID = (int)TempData["pid"];
            c.Muayanes.Add(muayane);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult PoliklinikSec()
        {
            var cc = c.Polikliniks.ToList();
            return View(cc);
        }

        [HttpGet]
        public IActionResult HastaEkle(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Kliniks.Where(x=>x.PoliklinikID == id).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KlinikAdı,
                                               Value = x.KlinikID.ToString()
                                           }).ToList();

            TempData["polinikID"] = id;

            ViewBag.dgr1 = deger1;
            return View();
        }

        [HttpPost]
        public IActionResult HastaEkle(Hasta p)
        {
            p.HastaTCNO = Encrypte.Encrypt(p.HastaTCNO);
            p.HastaSoyadı = Encrypte.Encrypt(p.HastaSoyadı);


            c.Hastas.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HastaneOtomasyonu/Views/HastaKayıt/HastaEkle.cshtml
@model HastaneOtomasyonu.EntityLayer.Models.Entity.Hasta

@{
    ViewData["Title"] = "HastaEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Hasta Kayıt</h1>
<br/>
<form class="form-group" method="post">
    @Html.LabelFor(x => x.HastaAdı)
    @Html.TextBoxFor(x => x.HastaAdı, new { @class = "form-control" })

    @Html.LabelFor(x => x.HastaSoyadı)
    @Html.TextBoxFor(x => x.HastaSoyadı, new { @class = "form-control" })    
    
    @Html.LabelFor(x => x.HastaTCNO)
    @Html.TextBoxFor(x => x.HastaTCNO, new { @class = "form-control" })       
    
    <br />
    @Html.LabelFor(x => x.KanGrubu)
    <select name="KanGrubu">
        <option value="A rh+">A rh+</option>
        <option value="A rh-">A rh-</option>
        <option value="B rh+">B rh+</option>
        <option value="B rh-">B rh-</option>        
        <option value="AB rh+">AB rh+</option>
        <option value="AB rh-">AB rh-</option>        
        <option value="O rh+">O rh+</option>
        <option value="O rh-">O rh-</option>
    </select>
    <br />
    <button type="submit">Kaydet</button>
</form>

HastaneOtomasyonu/Views/HastaKayıt/Index.cshtml
@model HastaneOtomasyonu.EntityLayer.Models.Entity.Hasta

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Hasta Kayıt</h1>
<br/>

@using (Html.BeginForm("Index", "HastaKayıt", FormMethod.Post))
{
    <div class="mb-3">
        <label class="form-label">Tc Kimlik No</label>
        @Html.TextBoxFor(x => x.HastaTCNO, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Gönder</button>
}

HastaneOtomasyonu/Views/HastaKayıt/PoliklinikSec.cshtml
@using HastaneOtomasyonu.EntityLayer.Models.Entity
@model List<Poliklinik>

@{
    ViewData["Title"] = "PoliklinikSec";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>PoliklinikSec</h1>
<br/>
<div class="table-responsive">
    <table class="table">
        <caption>List of Poliklinik</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Poliklinik Adı</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <th scope="row">@c.PoliklinikID</th>
                    <td>@c.PoliklinikAdı</td>
                    <td><a href="/HastaKayıt/Randevu/@c.PoliklinikID">Seç</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

HastaneOtomasyonu/Views/HastaKayıt/Randevu.cshtml
@using HastaneOtomasyonu.EntityLayer.Models.Entity
@model List<Klinik>

@{
    ViewData["Title"] = "Randevu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Randevu</h1>

<br />
<div class="table-responsive">
    <table class="table">
        <caption>List of Klinik</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Klinik Adı</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <th scope="row">@c.KlinikID</th>
                    <td>@c.KlinikAdı</td>
                    <td><a href="/HastaKayıt/RandevuAlındı/@c.KlinikID" class="btn btn-primary">Seç</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Klinikler/KlinikEkle/@ViewBag.id" class="btn btn-info">Ekle</a>
</div>